# Makefile — install scanner_dork.py as a `scanner-dork` command on your system.
#
#   make install     create an isolated venv + drop a `scanner-dork` launcher in ~/.local/bin
#   make check       confirm the launcher works (runs `scanner-dork --help`)
#   make reinstall   rebuild the launcher (e.g. after moving the repo)
#   make uninstall   remove the launcher and the venv
#
# The launcher points at THIS checkout, so edits to scanner_dork.py take effect
# immediately — no reinstall needed unless you move the repo.
#
# Override install location with PREFIX, e.g.:  make install PREFIX=$HOME/.local

SHELL   := /bin/bash
PREFIX  ?= $(HOME)/.local
BINDIR  := $(PREFIX)/bin
APPDIR  := $(PREFIX)/share/scanner-dork
VENV    := $(APPDIR)/venv
PY      := $(VENV)/bin/python
SRC     := $(abspath scanner_dork.py)
LAUNCH  := $(BINDIR)/scanner-dork

.PHONY: install venv launcher check reinstall uninstall

install: venv launcher
	@echo ""
	@echo "  Installed: $(LAUNCH)"
	@echo "  Try:       scanner-dork --engine netlas --mine domains.txt --net 203.0.113.0/24"
	@case ":$$PATH:" in *":$(BINDIR):"*) ;; \
	  *) echo ""; echo "  NOTE: $(BINDIR) is not on your PATH. Add to your shell rc:"; \
	     echo "        export PATH=\"$(BINDIR):\$$PATH\"";; esac

venv:
	@command -v python3 >/dev/null || { echo "python3 not found"; exit 1; }
	@mkdir -p $(APPDIR)
	@test -d $(VENV) || python3 -m venv $(VENV) || { \
	  echo "venv creation failed — you may need: sudo apt install python3-venv"; exit 1; }
	@$(PY) -m pip install --quiet --upgrade pip
	@$(PY) -m pip install --quiet -r $(abspath requirements.txt)
	@echo "venv ready: $(VENV)"

launcher:
	@mkdir -p $(BINDIR)
	@printf '#!/usr/bin/env bash\n# auto-generated by scanner-dork Makefile\nexec "%s" "%s" "$$@"\n' \
	  "$(PY)" "$(SRC)" > $(LAUNCH)
	@chmod +x $(LAUNCH)
	@echo "launcher -> $(LAUNCH)"

check:
	@test -x $(LAUNCH) || { echo "not installed — run: make install"; exit 1; }
	@$(LAUNCH) --help >/dev/null && echo "OK: $(LAUNCH) runs"

reinstall: launcher
	@echo "launcher rebuilt against $(SRC)"

uninstall:
	@rm -f $(LAUNCH)
	@rm -rf $(APPDIR)
	@echo "removed $(LAUNCH) and $(APPDIR)"

# ─── pentest-agent (staging) ────────────────────────────────────────────────
# `make install-stag` installs pentest-agent.py and the modules it imports
# (http_client, learn, and the wp/ package) as a `pentest-agent` command —
# separate from the scanner-dork targets above, so both tools coexist.
#
#   make install-stag     isolated venv + `pentest-agent` launcher + man page
#   make check-stag       confirm it works (runs `pentest-agent --version`)
#   make reinstall-stag   rebuild the launcher (e.g. after moving the repo)
#   make uninstall-stag   remove the launcher, man page, and its venv
#
# Like the scanner-dork launcher, this points at THIS checkout, so edits to any
# module (pentest-agent.py, wp/*.py, ...) take effect immediately — the launcher
# runs the script in place, so Python resolves the sibling modules and the wp/
# package straight from this repo.

STAG_APPDIR := $(PREFIX)/share/pentest-agent
STAG_VENV   := $(STAG_APPDIR)/venv
STAG_PY     := $(STAG_VENV)/bin/python
STAG_SRC    := $(abspath pentest-agent.py)
STAG_LAUNCH := $(BINDIR)/pentest-agent
STAG_MAN    := $(abspath pentest-agent.1)
STAG_MANDIR := $(PREFIX)/share/man/man1

.PHONY: install-stag venv-stag launcher-stag man-stag check-stag reinstall-stag uninstall-stag

install-stag: venv-stag launcher-stag man-stag
	@echo ""
	@echo "  ✓ Installed: $(STAG_LAUNCH)"
	@echo "    Try:       pentest-agent --version"
	@case ":$$PATH:" in *":$(BINDIR):"*) ;; \
	  *) echo ""; echo "  NOTE: $(BINDIR) is not on your PATH. Add to your shell rc:"; \
	     echo "        export PATH=\"$(BINDIR):\$$PATH\"";; esac

venv-stag:
	@echo "── Installing pentest-agent (staging) ──────────────────────────────"
	@echo "==> [1/3] Checking prerequisites"
	@command -v python3 >/dev/null || { echo "    ERROR: python3 not found"; exit 1; }
	@echo "    found $$(python3 --version 2>&1) at $$(command -v python3)"
	@mkdir -p $(STAG_APPDIR)
	@echo "==> [2/3] Preparing virtualenv at $(STAG_VENV)"
	@if [ -d $(STAG_VENV) ]; then \
	   echo "    reusing existing venv"; \
	 else \
	   echo "    creating venv (python3 -m venv)…"; \
	   python3 -m venv $(STAG_VENV) || { echo "    ERROR: venv creation failed — try: sudo apt install python3-venv"; exit 1; }; \
	   echo "    venv created"; \
	 fi
	@echo "==> [3/3] Installing dependencies into the venv"
	@echo "    - upgrading pip"
	@$(STAG_PY) -m pip install --upgrade pip
	@echo "    - installing from $(abspath requirements.txt)"
	@$(STAG_PY) -m pip install -r $(abspath requirements.txt)
	@echo "    dependencies present in venv:"
	@$(STAG_PY) -m pip list 2>/dev/null | grep -iE '^(requests|urllib3|certifi|idna|charset-normalizer) ' | sed 's/^/      /'
	@echo "    venv ready: $(STAG_VENV)"

launcher-stag:
	@echo "==> Writing launcher"
	@mkdir -p $(BINDIR)
	@printf '#!/usr/bin/env bash\n# auto-generated by pentest-agent Makefile (install-stag)\nexec "%s" "%s" "$$@"\n' \
	  "$(STAG_PY)" "$(STAG_SRC)" > $(STAG_LAUNCH)
	@chmod +x $(STAG_LAUNCH)
	@echo "    launcher -> $(STAG_LAUNCH)"
	@echo "    will run  -> (venv python) $(STAG_SRC)"

man-stag:
	@echo "==> Installing man page"
	@mkdir -p $(STAG_MANDIR)
	@cp $(STAG_MAN) $(STAG_MANDIR)/pentest-agent.1
	@echo "    man page -> $(STAG_MANDIR)/pentest-agent.1"
	@command -v mandb >/dev/null 2>&1 && mandb -q $(PREFIX)/share/man >/dev/null 2>&1 || true
	@echo "    try: man pentest-agent"

check-stag:
	@test -x $(STAG_LAUNCH) || { echo "not installed — run: make install-stag"; exit 1; }
	@$(STAG_LAUNCH) --version >/dev/null && echo "OK: $(STAG_LAUNCH) runs"

reinstall-stag: launcher-stag
	@echo "launcher rebuilt against $(STAG_SRC)"

uninstall-stag:
	@rm -f $(STAG_LAUNCH)
	@rm -f $(STAG_MANDIR)/pentest-agent.1
	@rm -rf $(STAG_APPDIR)
	@echo "removed $(STAG_LAUNCH), $(STAG_MANDIR)/pentest-agent.1 and $(STAG_APPDIR)"
