# Makefile.el — install scanner_dork.py (Shodan-only) as a `scanner-dork` command.
#
# Clean, self-contained build for THIS scanner only. Unlike the legacy Makefile,
# it installs the one real dependency (requests) directly — there is no
# requirements.txt, and no other tools are pulled in.
#
#   make -f Makefile.el install     isolated venv + `scanner-dork` launcher in ~/.local/bin
#   make -f Makefile.el check        confirm the launcher works (scanner-dork --version)
#   make -f Makefile.el test         run the scanner's own key/plan check (--test)
#   make -f Makefile.el reinstall    rebuild the launcher (e.g. after moving the repo)
#   make -f Makefile.el uninstall    remove the launcher and the venv
#
# The launcher points at THIS checkout, so edits to scanner_dork.py take effect
# immediately — no reinstall needed unless you move the repo.
#
# Override install location with PREFIX, e.g.:  make -f Makefile.el install PREFIX=$HOME/.local

SHELL   := /bin/bash
PREFIX  ?= $(HOME)/.local
BINDIR  := $(PREFIX)/bin
APPDIR  := $(PREFIX)/share/scanner-dork
VENV    := $(APPDIR)/venv
PY      := $(VENV)/bin/python
SRC     := $(abspath scanner_dork.py)
LAUNCH  := $(BINDIR)/scanner-dork

# The scanner's only third-party import; everything else is stdlib or the local
# agent_bridge.py module.
DEPS    := requests

.PHONY: install venv launcher check test reinstall uninstall

install: venv launcher
	@echo ""
	@echo "  Installed: $(LAUNCH)"
	@echo "  Try:       scanner-dork --test"
	@echo "             scanner-dork --mine domains.txt --country ID"
	@case ":$$PATH:" in *":$(BINDIR):"*) ;; \
	  *) echo ""; echo "  NOTE: $(BINDIR) is not on your PATH. Add to your shell rc:"; \
	     echo "        export PATH=\"$(BINDIR):\$$PATH\"";; esac

venv:
	@command -v python3 >/dev/null || { echo "python3 not found"; exit 1; }
	@mkdir -p $(APPDIR)
	@test -d $(VENV) || python3 -m venv $(VENV) || { \
	  echo "venv creation failed — you may need: sudo apt install python3-venv"; exit 1; }
	@$(PY) -m pip install --quiet --upgrade pip
	@$(PY) -m pip install --quiet $(DEPS)
	@echo "venv ready: $(VENV)"

launcher:
	@mkdir -p $(BINDIR)
	@printf '#!/usr/bin/env bash\n# auto-generated by Makefile.el (scanner-dork)\nexec "%s" "%s" "$$@"\n' \
	  "$(PY)" "$(SRC)" > $(LAUNCH)
	@chmod +x $(LAUNCH)
	@echo "launcher -> $(LAUNCH)"

check:
	@test -x $(LAUNCH) || { echo "not installed — run: make -f Makefile.el install"; exit 1; }
	@$(LAUNCH) --version && echo "OK: $(LAUNCH) runs"

test:
	@test -x $(LAUNCH) || { echo "not installed — run: make -f Makefile.el install"; exit 1; }
	@$(LAUNCH) --test

reinstall: launcher
	@echo "launcher rebuilt against $(SRC)"

uninstall:
	@rm -f $(LAUNCH)
	@rm -rf $(APPDIR)
	@echo "removed $(LAUNCH) and $(APPDIR)"
