# Makefile — install scanner_dork.py as a `scanner-dork` command on your system.
#
#   make install     create an isolated venv + drop a `scanner-dork` launcher in ~/.local/bin
#   make check       confirm the launcher works (runs `scanner-dork --help`)
#   make reinstall   rebuild the launcher (e.g. after moving the repo)
#   make uninstall   remove the launcher and the venv
#
# The launcher points at THIS checkout, so edits to scanner_dork.py take effect
# immediately — no reinstall needed unless you move the repo.
#
# Override install location with PREFIX, e.g.:  make install PREFIX=$HOME/.local

SHELL   := /bin/bash
PREFIX  ?= $(HOME)/.local
BINDIR  := $(PREFIX)/bin
APPDIR  := $(PREFIX)/share/scanner-dork
VENV    := $(APPDIR)/venv
PY      := $(VENV)/bin/python
SRC     := $(abspath scanner_dork.py)
LAUNCH  := $(BINDIR)/scanner-dork

.PHONY: install venv launcher check reinstall uninstall

install: venv launcher
	@echo ""
	@echo "  Installed: $(LAUNCH)"
	@echo "  Try:       scanner-dork --engine netlas --mine domains.txt --net 203.0.113.0/24"
	@case ":$$PATH:" in *":$(BINDIR):"*) ;; \
	  *) echo ""; echo "  NOTE: $(BINDIR) is not on your PATH. Add to your shell rc:"; \
	     echo "        export PATH=\"$(BINDIR):\$$PATH\"";; esac

venv:
	@command -v python3 >/dev/null || { echo "python3 not found"; exit 1; }
	@mkdir -p $(APPDIR)
	@test -d $(VENV) || python3 -m venv $(VENV) || { \
	  echo "venv creation failed — you may need: sudo apt install python3-venv"; exit 1; }
	@$(PY) -m pip install --quiet --upgrade pip
	@$(PY) -m pip install --quiet -r $(abspath requirements.txt)
	@echo "venv ready: $(VENV)"

launcher:
	@mkdir -p $(BINDIR)
	@printf '#!/usr/bin/env bash\n# auto-generated by scanner-dork Makefile\nexec "%s" "%s" "$$@"\n' \
	  "$(PY)" "$(SRC)" > $(LAUNCH)
	@chmod +x $(LAUNCH)
	@echo "launcher -> $(LAUNCH)"

check:
	@test -x $(LAUNCH) || { echo "not installed — run: make install"; exit 1; }
	@$(LAUNCH) --help >/dev/null && echo "OK: $(LAUNCH) runs"

reinstall: launcher
	@echo "launcher rebuilt against $(SRC)"

uninstall:
	@rm -f $(LAUNCH)
	@rm -rf $(APPDIR)
	@echo "removed $(LAUNCH) and $(APPDIR)"

# ─── pentest-agent (staging) ────────────────────────────────────────────────
# `make install-stag` installs pentest-agent.py and the modules it imports
# (http_client, learn, and the wp/ package) as a `pentest-agent` command —
# separate from the scanner-dork targets above, so both tools coexist.
#
#   make install-stag     create an isolated venv + drop a `pentest-agent` launcher
#   make check-stag       confirm it works (runs `pentest-agent --version`)
#   make reinstall-stag   rebuild the launcher (e.g. after moving the repo)
#   make uninstall-stag   remove the launcher and its venv
#
# Like the scanner-dork launcher, this points at THIS checkout, so edits to any
# module (pentest-agent.py, wp/*.py, ...) take effect immediately — the launcher
# runs the script in place, so Python resolves the sibling modules and the wp/
# package straight from this repo.

STAG_APPDIR := $(PREFIX)/share/pentest-agent
STAG_VENV   := $(STAG_APPDIR)/venv
STAG_PY     := $(STAG_VENV)/bin/python
STAG_SRC    := $(abspath pentest-agent.py)
STAG_LAUNCH := $(BINDIR)/pentest-agent

.PHONY: install-stag venv-stag launcher-stag check-stag reinstall-stag uninstall-stag

install-stag: venv-stag launcher-stag
	@echo ""
	@echo "  Installed: $(STAG_LAUNCH)"
	@echo "  Try:       pentest-agent --version"
	@case ":$$PATH:" in *":$(BINDIR):"*) ;; \
	  *) echo ""; echo "  NOTE: $(BINDIR) is not on your PATH. Add to your shell rc:"; \
	     echo "        export PATH=\"$(BINDIR):\$$PATH\"";; esac

venv-stag:
	@command -v python3 >/dev/null || { echo "python3 not found"; exit 1; }
	@mkdir -p $(STAG_APPDIR)
	@test -d $(STAG_VENV) || python3 -m venv $(STAG_VENV) || { \
	  echo "venv creation failed — you may need: sudo apt install python3-venv"; exit 1; }
	@$(STAG_PY) -m pip install --quiet --upgrade pip
	@$(STAG_PY) -m pip install --quiet -r $(abspath requirements.txt)
	@echo "venv ready: $(STAG_VENV)"

launcher-stag:
	@mkdir -p $(BINDIR)
	@printf '#!/usr/bin/env bash\n# auto-generated by pentest-agent Makefile (install-stag)\nexec "%s" "%s" "$$@"\n' \
	  "$(STAG_PY)" "$(STAG_SRC)" > $(STAG_LAUNCH)
	@chmod +x $(STAG_LAUNCH)
	@echo "launcher -> $(STAG_LAUNCH)"

check-stag:
	@test -x $(STAG_LAUNCH) || { echo "not installed — run: make install-stag"; exit 1; }
	@$(STAG_LAUNCH) --version >/dev/null && echo "OK: $(STAG_LAUNCH) runs"

reinstall-stag: launcher-stag
	@echo "launcher rebuilt against $(STAG_SRC)"

uninstall-stag:
	@rm -f $(STAG_LAUNCH)
	@rm -rf $(STAG_APPDIR)
	@echo "removed $(STAG_LAUNCH) and $(STAG_APPDIR)"
